# Test cases for model template rendering

# Token definitions
[tokens]
bos_token = "BOS_"
eos_token = "_EOS"
sep_token = "<|>"

# test cases
[test_cases."user>ai"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
]

[test_cases.empty]
messages = []

[test_cases."just user"]
messages = [{ role = "user", content = "Hello!" }]

[test_cases."user>ai>user"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
]

[test_cases."user>ai>user>user"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
    { role = "user", content = "How many cats are there in the world?" },
]

[test_cases."invalid role"]
messages = [{ role = "invalid", content = "Hello!" }]

[test_cases.tools]
messages = [
    { role = "user", content = "Hello!" },
    { role = "tool", content = "derp", tool_calls_json = "[{'name': 'tool_name', 'arguments': 'example_arg: 1.0, another_example_arg: true', 'type': 'function'}]" },
    { role = "assistant", content = "Hello! How can I help you today?" },
]
tools_json = '[{"name": "tool_name", "arguments": "example_arg: 1.0, another_example_arg: true", "type": "function"}]'

[test_cases."think user>ai"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "<think>\nHmm, let me think...\n</think>\nHi! How can I help you today?" },
]

[test_cases."think user>ai>user"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "<think>\nHmm, let me think...\n</think>\nHi! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
]
