# Test cases for model template rendering

# Token definitions
[tokens]
bos_token = "BOS_"
eos_token = "_EOS"
sep_token = "<|>"

# Basic test with simple user and assistant messages
[test_cases.basic]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
]

# Empty test case with no messages
[test_cases.empty]
messages = []

# User message as the last message in the conversation
[test_cases."user last"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
]

# Test case with two user messages in sequence
[test_cases."double user"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "Hello! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
    { role = "user", content = "How many cats are there in the world?" },
]

# Test case with an invalid role
[test_cases."invalid role"]
messages = [{ role = "invalid", content = "Hello!" }]

# Test case with tool calls
[test_cases.tools]
messages = [
    { role = "user", content = "Hello!" },
    { role = "tool", content = "derp", tool_calls_json = "[{'name': 'tool_name', 'arguments': 'example_arg: 1.0, another_example_arg: true', 'type': 'function'}]" },
    { role = "assistant", content = "Hello! How can I help you today?" },
]
tools_json = '[{"name": "tool_name", "arguments": "example_arg: 1.0, another_example_arg: true", "type": "function"}]'

# Test case with thinking tag in assistant response
[test_cases."think basic"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "<think>Hmm, let me think...</think>Hi! How can I help you today?" },
]

# Test case with thinking tag and user as last message
[test_cases."think user last"]
messages = [
    { role = "user", content = "Hello!" },
    { role = "assistant", content = "<think>Hmm, let me think...</think>Hi! How can I help you today?" },
    { role = "user", content = "What is the weather in Tokyo?" },
]
